name: Participant Registration
description: Register as a current Level Up participant
title: "ACCESS REQUEST"
labels: ["register"]
assignees:
  - octocat
body:
  - type: input
    id: contact
    attributes:
      label: First and Last Name
      description: Give us your first and last name, if you're comfortable. Otherwise, email DevRel@wellsfargo.com once you've registered and what your GitHub ID is.
      placeholder: Firstname Lastname
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Which session are you attending? If unknown, contact DevRel@wellsfargo.com.
      options:
      - 4/26 week in Charlotte
      - 5/16 week in San Fransisco
      - 6/6 week in Chandler
      - 8/8 week in Des Moines
      - 9/12 week in Charlotte
      - 10/17 week in San Fransisco
      - 11/14 week in Chandler
        required: true
  - type: checkboxes
    id: photorelease
    attributes:
      label: Photo Release
      description: By checking this box, I grant the right to photograph, film, or otherwise record me during this workshop.
      options:
        - label: I authorize photo release
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to use this repository only for LevelUp classroom work and not for any confidential or private company information.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
